{
 "title": "user-service-dashboard",
 "time": { "from": "2021-02-23T20:45:00.000Z", "to": "2021-02-23T21:05:00.000Z" },
 "panels": [
  {
   "title": "nginx 500 error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "server 500  error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{status=\"500\"}[1m])"
    }
   ]
  },
  {
   "title": "postgres cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"postgres-metrics\"}[1m])"
    }
   ]
  },
  {
   "title": "server error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{outcome=\"CLIENT_ERROR\"}[1m])"
    }
   ]
  },
  {
   "title": "nginx latency quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "latency quantile 0.5 get users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/users/{id}\"}[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "nginx latency quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "latency quantile 0.95 get users",
   "type": "graph",
   "description": "quantile 0.95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/users/{id}\"}[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "nginx latency quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "latency quantile 0.99 get users",
   "type": "graph",
   "description": "quantile 0.99",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/users/{id}\"}[1m]))) * 1000"
    }
   ]
  },
  {
   "title": "rps getUsers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(method_timed_seconds_count{method=\"getUserById\"}[1m]))"
    }
   ]
  },
  {
   "title": "rps nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "pods cpu usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"user-chart\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "rps server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "pods memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"user-chart\"}) by (pod)"
    }
   ]
  }
 ]
}