fullnameOverride: postgres-billing
postgresqlDatabase: billing_db
postgresqlUsername: srv.user
postgresqlPassword: srvpass

service:
  type: NodePort
  port: 5433

persistence:
  enabled: true
  size: 500m

resources:
  requests:
    memory: 256Mi
    cpu: 250m
