apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  db_port: {{ .Values.dbValues.port | quote }}
  db_host: {{ .Values.dbValues.host }}
  db_name: {{ .Values.dbValues.name }}
  billing_service_path: {{ .Values.billingService.path | quote }}
  delivery_service_path: {{ .Values.deliveryService.path | quote }}
  product_service_path: {{ .Values.productService.path | quote }}
  warehouse_service_path: {{ .Values.warehouseService.path | quote }}
  bootstrap_servers: {{ .Values.kafka.bootstrapServers | quote }}
  application.properties: {{ range .Files.Lines "application.properties" }}
    {{ . }}{{ "\n" }}{{ end }}
