apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  db_port: {{ .Values.dbValues.port | quote }}
  db_host: {{ .Values.dbValues.host }}
  db_name: {{ .Values.dbValues.name }}
  auth_service_path: {{ .Values.authService.path | quote }}
  application.properties: {{ range .Files.Lines "application.properties" }}
    {{ . }}{{ "\n" }}{{ end }}
