apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "notification-service.selectorLabels" . | nindent 4 }}
