apiVersion: v1
kind: Service
metadata:
  name: {{ include "billing-chart.fullname" . }}
  labels:
    {{- include "billing-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "billing-chart.selectorLabels" . | nindent 4 }}
