apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  rules:
    - host: "arch.homework"
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
