replicaCount: 2

image:
  repository: bogdanluk/notification-service
  pullPolicy: IfNotPresent
  tag: v1
probe:
  path: /actuator/health

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

kafka:
  bootstrapServers: "kafka.infrastructure.svc.cluster.local:9092"

dbValues:
  port: 5432
  host: postgres-notification.postgres
  name: notification_db

postgresImage: postgres:latest
postgresqlUsername: srv.user
postgresqlPassword: srvpass
jwtSecret: XLqmshiYH9lzhWROHGzGscTDZmBigwqiqB135aiT9R+sTTCXDu+axuaZBKMHgwEATlXcRq0nhRlfvQambcDQ4g==
