apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-service.fullname" . }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "product-service.selectorLabels" . | nindent 4 }}
