apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  db_username: {{ .Values.postgresqlUsername | b64enc | quote }}
  db_password: {{ .Values.postgresqlPassword | b64enc | quote }}
  jwt_secret: {{ .Values.jwtSecret | b64enc | quote }}
