apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      location /users/ {
        proxy_pass http://user-service.users:8080/api/;
      }

      location /auth/ {
        proxy_pass http://user-service-auth.auth:8080/api/;
      }
    }
