fullnameOverride: postgres
postgresqlDatabase: user_service
postgresqlUsername: srv.user
postgresqlPassword: srvpass

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 500m

resources:
  requests:
    memory: 256Mi
    cpu: 250m
